services:
  barcodebuddy:
    image: f0rc3/barcodebuddy:latest
    container_name: barcodebuddy
    environment:
      - BBUDDY_GROCERY_API_URL=http://192.168.0.114:5002
    ports:
      - "8000:80"
      - "4433:443"
    volumes:
      - bbconfig:/config
      - .:/app/bbuddy
      - bb_git_null:/app/bbuddy/.git
    restart: unless-stopped

volumes:
  bbconfig:
  bb_git_null:
